Title: Bahadar Srichawla
logo: https://github.com/Bsrichawla/bsrichawla.github.io/blob/main/assets/283184974_1044769786245304_8379700055209004969_n.jpg
author: "Bahadar Srichawla"
description: "University of Massachusetts Chan Medical School"
lang: "en"
show_downloads: True
theme: jekyll-theme-minimal

external:
  - {title: Mail, icon: envelope, url: "mailto:bahadar.srichawla@umassmemorial.org"}
  - {title: Github, icon: github, url: "https://github.com/bsrichawla"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/BSrichawlaDO"}

plugins:
 - jekyll-feed
