Title: "Bahadar Srichawla"
author: "Bahadar Srichawla"
description: "University of Massachusetts Chan Medical School"
lang: "en"
show_downloads: True
theme: jekyll-theme-minimal

external:
  - {title: Mail, icon: envelope, url: "mailto:bahadar.srichawla@umassmemorial.org"}
  - {title: Github, icon: github, url: "https://github.com/bsrichawla"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/BSrichawlaDO"}

plugins:
 - jekyll-feed
